### ISSUE TITLE
[NoDelete] Fic own messages getting deleted

### ISSUE THREAD

**Issue by Angelix1** [Meqativ/dumsane#2]
## Change how the system work by replacing on how we store the data and adding flags for it, due the event firing twice.
# changes
- Replace how we store the datas
```js
let delet = {}; 
```
- Delet data example
```js
// type Object {}
{
  "<EventID>" : {
    "arg": "<MessageDataArguments[Array]>",
    "flag": "< 1 | 2 >" // 1 = Cached and modified, 2 = Good for deletion
  }
}
```
- **Error Message for dismissable Message**, this can be modified before all checks occured.
```js
let message = "This message was deleted";
```
## First Check
- Check if the Message already been cached before or not, if not we push it into `delet` with several datas in it and modify the message to RED Error message that dismissable.
```js
if( !delet[event.id] ) {
  args[0] = {
    type: "MESSAGE_EDIT_FAILED_AUTOMOD",
    messageData: {
      type: 1,
      message: {
        channelId: event.channelId,
        messageId: event.id,
      },
    },
    errorResponseBody: {
      code: 200000,
      message,
    },
  };
  delet[event.id] = {
    arg: args,
    flag: 1
  };
  return args;
}
```
## Second Check
- used to handle the followed up event with the same Id and prevent it to delete the already modified message we do on first check, so i create this check that check if it already available on `delet` and then if the flag of said id is `1`, if both statement is `true` then we update the flag to `2`, then we replace the msg with `arg` that contains the modified version to avoid it deleting the msg by accident, basically forcing it to not deleting it by updating it with the same stuff, _this works for no reason_
```js
if( delet[event.id] && delet[event.id]['flag'] == 1 ) {
  delet[event.id]['flag'] = 2;
  return delet[event.id]["arg"];
};
```
## Third Check
- here we check if it exist on `delet`, and if the flag is `2`, if statements are true, then we just delete the key from `delet` and remove the message.
```js
if( delet[event.id] && delet[event.id]['flag'] == 2 ) {
  delete delet[event.id], delet;
  return args;
}
```

**Comment by meqativ** [comment]
<details>
<summary> This leaves a unintended side effect </summary>

(you need to press `Dismiss message` 6 times)

</details>
which is worse than the issue it resolves imo<img src="https://cdn.discordapp.com/emojis/1088377519260045395.webp?size=4096" width="48" alt="skulley"/>
